#!/usr/bin/env bash
#SBATCH --job-name=blimmp_spliced
#SBATCH --output=logs/blimmp_%A_%a.out
#SBATCH --error=logs/blimmp_%A_%a.err
#SBATCH --time=00:20:00
#SBATCH --mem-per-cpu=8GB
#SBATCH --cpus-per-task=4
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --account=twheeler
#SBATCH --partition=standard
#SBATCH --array=0-166
set -eo pipefail

# ---- Env ----
set +u
source /home/u13/nsontakke/miniconda3/etc/profile.d/conda.sh
conda activate blimmp-work
set -u

# ---- Config ----
BASE_DIR="/xdisk/twheeler/nsontakke/Removal_Study_BLIMMP"
HMMSEARCH_ROOT="$BASE_DIR/HMMSEARCH_SPLICED"
OUT_ROOT="$BASE_DIR/BLIMMP_SPLICED"
WRAPPER="$BASE_DIR/BLIMMP_8Sep2026/blimmp_puma_wrapper.py"

# BUSCO completeness lookup — format: sample_name,completeness_decimal
# Generated by run_busco_spliced_array.sh → BUSCO_SPLICED/busco_completeness.tsv
BUSCO_TSV="$BASE_DIR/BUSCO_SPLICED/busco_completeness.tsv"

mkdir -p "$BASE_DIR/logs" "$OUT_ROOT"

# ---- Discover domtblout files ----
mapfile -t all_domtbl < <(find "$HMMSEARCH_ROOT" -name "*_spliced.domtblout" | sort)
TOTAL=${#all_domtbl[@]}
echo "[$SLURM_ARRAY_TASK_ID] Total domtblout files found: $TOTAL"

if (( TOTAL == 0 )); then
    echo "ERROR: No domtblout files in $HMMSEARCH_ROOT — run run_hmmsearch_spliced.sh first."
    exit 1
fi

if (( SLURM_ARRAY_TASK_ID >= TOTAL )); then
    echo "[$SLURM_ARRAY_TASK_ID] No file for this task index (total=$TOTAL)."
    exit 0
fi

domtbl="${all_domtbl[$SLURM_ARRAY_TASK_ID]}"
base=$(basename "$(dirname "$domtbl")")

SAMPLE_OUT="$OUT_ROOT/$base"
mkdir -p "$SAMPLE_OUT"

echo "[$SLURM_ARRAY_TASK_ID] Sample     : $base"
echo "[$SLURM_ARRAY_TASK_ID] domtblout  : $domtbl"
echo "[$SLURM_ARRAY_TASK_ID] Output dir : $SAMPLE_OUT"

# ---- Look up BUSCO-derived sigma ----
if [[ -f "$BUSCO_TSV" ]]; then
    sigma=$(awk -F',' -v s="$base" '$1 == s {print $2; exit}' "$BUSCO_TSV")
fi

if [[ -z "${sigma:-}" ]]; then
    echo "[$SLURM_ARRAY_TASK_ID] WARNING: No BUSCO completeness found for '$base' in $BUSCO_TSV — falling back to sigma=0.99" >&2
    sigma="0.99"
fi

# Skip samples with zero completeness (100% removed genomes — no genes remain)
if (( $(echo "$sigma == 0.0" | bc -l) )); then
    echo "[$SLURM_ARRAY_TASK_ID] SKIP: sigma=0.0 for $base (100% removed — no content to analyse)"
    exit 0
fi

echo "[$SLURM_ARRAY_TASK_ID] Sigma      : $sigma (BUSCO-derived)"

# ---- Skip if already done ----
PREFIX="$SAMPLE_OUT/${base}_"
if [[ -s "${PREFIX}module_probabilities_v2.tsv" ]]; then
    echo "[$SLURM_ARRAY_TASK_ID] SKIP: output already exists (${PREFIX}module_probabilities_v2.tsv)"
    exit 0
fi

# ---- Run BLIMMP ----
python "$WRAPPER" \
    "$domtbl" \
    -f domtblout \
    --sigma "$sigma" \
    --output "$PREFIX" \
    --verbose

echo "[$SLURM_ARRAY_TASK_ID] DONE: $base"
ls "$SAMPLE_OUT/"
